# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 56e8180
_src_path: https://github.com/vivienm/copier-rust
author_name: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_year: 2024
github_account: vivienm
github_pages: true
hosting_platform: github
license: MIT
package_name: nominal
project_description: A Rust library for batch file renaming.
project_name: nominal
project_type: library
repo_name: rust-nominal
rust_toolchain: stable
