[advisories]
version = 2

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
  "Unicode-DFS-2016",
]

[[licenses.exceptions]]
name = "nominal"
allow = ["MIT"]
